In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("/Users/ruank6/Desktop/Payments.csv")

In [24]:
pd.crosstab([df.DD,df.CPA,df.EP,df.PR,df.GS,df.DCP,df.DCA],df.OTHER,margins=True)

OTHER                      0   1  All
DD  CPA EP PR GS DCP DCA
0   0   0  0  0  1   0     1   0    1
           1  0  0   0     1   0    1
        1  1  0  1   1     1   0    1
              1  1   0     1   0    1
                     1     0   1    1
    1   0  0  0  1   0     1   0    1
           1  0  1   0     1   0    1
        1  0  0  0   0     0   1    1
                     1     0   1    1
                 1   0     0   1    1
              1  0   0     0   1    1
1   0   0  0  0  0   0     1   0    1
              1  1   1     1   0    1
           1  0  1   1     1   0    1
        1  0  1  0   0     0   1    1
           1  0  1   1     1   1    2
              1  0   0     1   0    1
    1   0  0  1  1   0     0   1    1
                     1     1   0    1
           1  0  0   1     1   0    1
              1  1   0     1   0    1
        1  1  1  0   0     0   2    2
All                       14  10   24